# Application port.
server:
  port: 8080

# Application name.
spring:
  profiles:
    active: path
  application:
    name: gateway
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.web: DEBUG
