# Zippy microservice profile.
server:
  port: 0

# Eureka client properties
eureka:
  client:
    enabled: true

spring:
  application:
    name: zippy

  # Common Database properties
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:///zippy;DB_CLOSE_ON_EXIT=TRUE
  sql:
    init:
      platform: h2
      username: sa
      password:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  # Allow use of H2 console at localhost:port/h2-console for debugging.
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
